### ISSUE TITLE
It can only access by root

### ISSUE THREAD

**Issue by fengcai123** [awslabs/mountpoint-s3#469] opened 2023-08-21 18:51 UTC
### Mountpoint for Amazon S3 version

mount-s3 1.0.0

### Describe the running environment

I mounts the bucket. But I cannot change owner or chmod on the directory, it can be accessed by root, but not other IDS. 
My plan is to used it for database backup .

### What happened?

Allow other users to use it

### Relevant log output

```shell
Aug 21 18:47:05 ip-172-31-27-36.ec2.internal mount-s3[17457]: [WARN] setattr{req=20 ino=1}: mountpoint_s3::fuse: setattr failed: inode error: inode 1 (full key "") is a remote
Aug 21 18:47:26 ip-172-31-27-36.ec2.internal mount-s3[17457]: [WARN] setattr{req=22 ino=1}: mountpoint_s3::fuse: setattr failed: inode error: inode 1 (full key "") is a remote
~
```

**Comment by ahmarsuhail** [comment] 2023-08-22 14:27
Mountpoint applies default permissions that allow all files in your mounted directory to be read and written by the local user who ran the mount-s3 command. If you want to use it with a particular user, you could consider mounting with this user.

If you still want to mount with the root user, and allow other users access, you can use the `--allow-other `command, and also set the correct permissions using `--file-mode`. For more info, you can refer to the [documentation](https://github.com/awslabs/mountpoint-s3/blob/main/doc/CONFIGURATION.md#file-and-directory-permissions) on file and directory permissions.

**Comment by dannycjones** [comment] 2023-09-14 13:08
Closing this, please re-open or open a new issue if the problem isn't resolved. Thanks!

**Closed by dannycjones** 2023-09-14 13:08 UTC
Labels: bug
