### ISSUE TITLE
Make it available for any S3 compatible back-end storage 

### ISSUE THREAD

**Issue by debnsuma** [awslabs/mountpoint-s3#146] opened 2023-03-14 20:02 UTC
### Tell us more about this new feature.

This is a fantastic project, it would be nice if we can have it compatible with any S3 compatible storage in future.

**Comment by virtualirfan** [comment] 2023-03-14 20:35
Looks like a duplicate of #144

**Comment by debnsuma** [comment] 2023-03-14 20:36
Yes, i just realized it after creating this request.

**Comment by jamesbornholt** [comment] 2023-03-14 23:04
Thanks! Going to close this in favor of #144, which has some pointers on compatibility.

**Closed by jamesbornholt** 2023-03-14 23:04 UTC
Labels: enhancement
