### ISSUE TITLE
mount-point connection refused error

### ISSUE THREAD

**Issue by SonJunYoung354** [awslabs/mountpoint-s3#617] opened 2023-11-21 07:47 UTC
### Mountpoint for Amazon S3 version

mount-s31.1.1

### AWS Region

ap-northeast-2

### Describe the running environment

ec2 instance RHEL 7.5OS

### What happened?

bash command : mount-s3 {s3_bucket_name} {mount_path}
return : connection refused

SYSLOG message 
mount_s3 successfully mounted bucket {bucket_name} at {mount_path} 
fuser:: requst: Request Requestid(1): Failed to send reply : Invalid argument(os error 22)
ec2 profile aws3 ls and aws3 cp commands are possible

I'm curious about the cause of the error.

Syslog

Nov 1 18:20:30 {hostname} mount-s3[5423] [DEBUG] mountpoint_s3::instance: got instance info from IMDS identity_document { instance_type "m5.4xlarge", region: "ap-northeast2-2"

Nov 1 18:20:30 {hostname} mount-s3[5423] [INFO] mouint_s3: target network throughput 10 Gbps
Nov 1 18:20:30 {hostname} mount-s3[5423] [DEBUG] moubnt_s3: using instance region ap-northeast-2
Nov 1 18:20:30 {hostname} mount-s3[5423] [DEBUG] list_objects{id=0 bucket=temp0810 contiuned=false delimiter= max_keys=0  prefix=} mountpoint_s3_client:;s3:crt_client::list_objects: new request
Nov 1 18:20:30 {hostname} mount-s3[5423] [DEBUG] list_objects{id=0 bucket=temp0810 contiuned=false delimiter= max_keys=0  prefix=} mountpoint_s3_client:;s3:crt_client:: request finished request_type=Default http_status=200 range=None duration=36.368727ms ttfb=Some(24.582261ms) request_id=MN4124423QX5VQRG
Nov 1 18:20:30 {hostname} mount-s3[5423] [DEBUG] list_objects{id=0 bucket=temp0810 contiuned=false delimiter= max_keys=0  prefix=} mountpoint_s3_client:;s3:crt_client:: meta request finished duration=36.60ms
Nov 1 18:20:30 {hostname} mount-s3[5423] [INFO] fuser:session: Mounting {mount_path}
Nov 1 18:20:30 {hostname} mount-s3[5423] [INFO] mount_s3: successfully mounted bucekt temp0810 at {mount_path}
Nov 1 18:20:30 {hostname} mount-s3[5423] [DEBUG] mountpint_s3::fuse:session: starting fuse worker 0 (thread id 5426)
Nov 1 18:20:30 {hostname} mount-s3[5423] [DEBUG] fuser::request: FUSE( 1) ino 0X0000000000000000 INIT kernal ABI 7.22, cAPABILITIES 0xf7fb, max readahead 131072
Nov 1 18:20:30 {hostname} mount-s3[5423] [DEBUG] mountpint_s3::fuse:session: starting fuse worker 0 (thread id 5428)
Nov 1 18:20:30 {hostname} mount-s3[5423] [DEBUG] fuser::request:  INIT kernal ABI 7.22,flags 0x2021 max readahead 131072, max write 16777216
Nov 1 18:20:30 {hostname} mount-s3[5423] [DEBUG] mount_s3: success status flag received from child process
Nov 1 18:20:30 {hostname} mount-s3[5423] [INFO] mountpint_s3::metrics: fuse.op_latency_us[op=init]: n1: min=22 p10=22 p50=22 avg=22.00 p90=22 p99=22 p99.9=22 max=22
Nov 1 18:20:30 {hostname} mount-s3[5423] [INFO] mountpint_s3::metrics: s3.client.num_auto_default_network_id: 0
Nov 1 18:20:30 {hostname} mount-s3[5423] [INFO] mountpint_s3::metrics: s3.client.num_auto_ranged_copy_network_id: 0
Nov 1 18:20:30 {hostname} mount-s3[5423] [INFO] mountpint_s3::metrics: s3.client.num_auto_ranged_get_network_id: 0
Nov 1 18:20:30 {hostname} mount-s3[5423] [INFO] mountpint_s3::metrics: s3.client.num_auto_ranged_put_network_id: 0
Nov 1 18:20:30 {hostname} mount-s3[5423] [INFO] mountpint_s3::metrics: s3.client.num_requests_being_prepared: 0 
Nov 1 18:20:30 {hostname} mount-s3[5423] [INFO] mountpint_s3::metrics: s3.client.num_requests_being_processed: 0 
Nov 1 18:20:30 {hostname} mount-s3[5423] [INFO] mountpint_s3::metrics: s3.client.num_requests_stream_queued_waiting: 0 
Nov 1 18:20:30 {hostname} mount-s3[5423] [INFO] mountpint_s3::metrics: s3.client.num_requests_streaming_response: 0
Nov 1 18:20:30 {hostname} mount-s3[5423] [INFO] mountpint_s3::metrics: s3.client.num_total_network_io: 0
Nov 1 18:20:30 {hostname} mount-s3[5423] [INFO] mountpint_s3::metrics: s3.client.reuest_queue_size: 0

bash command : mount-s3 {s3_bucket_name} {mount_path}
return : connection refused

**Comment by SonJunYoung354** [comment] 2023-11-28 01:52
Hello log message commit

**Comment by Tom9729** [comment] 2023-11-29 01:44
We are seeing the same issue on CentOS 7.4 with the RPM from the releases page, but it works as expected on AlmaLinux 8.8. 

Will report if a newer version of CentOS 7 or building from source works...

**Comment by dannycjones** [comment] 2023-12-11 16:57
> We are seeing the same issue on CentOS 7.4 with the RPM from the releases page, but it works as expected on AlmaLinux 8.8.
> 
> Will report if a newer version of CentOS 7 or building from source works...

Hey @Tom9729, do you mind opening a new bug report if you still see the issue? Information specific to your error (which version, logs, etc) will help to identify root cause.

**Comment by dannycjones** [comment] 2023-12-29 13:41
I'll close this issue for now. If you have any more information, please do re-open or open a new issue.

**Closed by dannycjones** 2023-12-29 13:41 UTC
Labels: bug
