### ISSUE TITLE
umount consistency issue

### ISSUE THREAD

**Issue by jchorl** [awslabs/mountpoint-s3#435] opened 2023-08-07 01:07 UTC
### Mountpoint for Amazon S3 version

Sha: 59f2ebbc786d98796e387a717e620d59e4853329

### AWS Region

ca-central-1

### Describe the running environment

I was playing around with the consistency semantics of mountpoint. I wrote a driver to:
1. Mount prefix from s3
2. `cp` a file to the mount
3. `umount` the mount target
4. `head-object` the newly written file

This failed. I read through https://github.com/awslabs/mountpoint-s3/blob/main/doc/SEMANTICS.md - I saw the part about calling `fsync`.

This case feels different. I understand that filesystems can have some lag, so `fsync` is useful. However [this](https://unix.stackexchange.com/a/345950) seems to indicate that at least `umount` should `sync` and finish pending writes. I commented out a `sleep` in my driver - uncommenting this fixes the issue.

So now the question - is this behaviour expected? What should we expect semantically from `umount`? Are there magic flags we can pass to make this consistent?

Here's how I set up the driver:

Cloned mountpoint s3, built from source. Commit: 59f2ebbc786d98796e387a717e620d59e4853329

On a pretty recent amazon-linux-2:

```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
source "$HOME/.cargo/env"
git clone --recurse-submodules https://github.com/awslabs/mountpoint-s3.git
cd mountpoint-s3
sudo yum install fuse fuse-devel cmake3 clang git pkg-config
cargo build --release
sudo su
python3 -m ensurepip --upgrade
python3 -m pip install boto3
```

The driver:
```python
import boto3
import subprocess
import tempfile
import time


client = boto3.client("s3")
mountpoint_bin = "/path/to/mountpoint-s3/target/release/mount-s3"
bucket = "my-s3-bucket"
prefix = "my-s3-prefix/"
test_file = "sample_file.txt"
key = f"{prefix}{test_file}"


def prep():
    with open(test_file, "w") as f:
        f.write("a" * 15252636)


def run_test():
    with tempfile.TemporaryDirectory() as tmpdir:
        subprocess.run([
            mountpoint_bin,
            bucket,
            tmpdir,
            "--prefix",
            prefix,
        ], check=True)
        subprocess.run(["cp", test_file, tmpdir + f"/{test_file}"], check=True)
        subprocess.run(["umount", tmpdir], check=True)
        # uncomment to pass
        # time.sleep(3)


def check_failure():
    resp = client.head_object(
        Bucket=bucket,
        Key=key,
    )
    assert resp["ETag"] == '"2e3f2cfa86aa3100ff361e27160eb961-2"'


def cleanup():
    client.delete_object(
        Bucket=bucket,
        Key=key,
    )


def main():
    prep()
    cleanup()
    for i in range(100):
        run_test()
        check_failure()
        cleanup()


if __name__ == "__main__":
    main()
```

Then just run it:
```
python3 driver_raw.py
```

### What happened?

The `head-object` failed.

### Relevant log output

```shell
Unsure if relevant:

2023-08-07T00:31:26+0000 mount-s3[14062]: [DEBUG] release{req=244 ino=2 fh=1}: mountpoint_s3::fs: put succeeded key=myprefix/mykey size=15252636
2023-08-07T00:31:26+0000 mount-s3[14062]: [ERROR] release{req=244 ino=2 fh=1}: fuser::reply: Failed to send FUSE reply: No such file or directory (os error 2)
2023-08-07T00:31:26+0000 mount-s3[14062]: [INFO] fuser::session: Unmounted /tmp/tmpix01vnf9
2023-08-07T00:31:26+0000 mount-s3[14062]: [WARN] fuser::mnt::fuse2: umount failed with Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

**Comment by passaro** [comment] 2023-08-07 16:38
Hi @jchorl, thank you for opening this issue. 

The expected behavior when calling `umount` after closing a file is that the upload will complete. By looking at the logs you posted, it seems this is indeed what happens:
```
2023-08-07T00:31:26+0000 mount-s3[14062]: [DEBUG] release{req=244 ino=2 fh=1}: mountpoint_s3::fs: put succeeded key=myprefix/mykey size=15252636
```
(note that the subsequent messages in the log show that mountpoint detected the `umount` after the put succeeded)

The issue you are seeing seems due to the `head_object` request being issued **before** the put has completed. That is because there is no guarantee that Mountpoint has finished uploading the object by the time `umount` returns. This is a limitation of FUSE: `umount` does not wait for the Mountpoint daemon to indicate it is ready to be unmounted, so there is no way for it to block until the upload is complete.

**Comment by jchorl** [comment] 2023-08-07 17:41
Thanks for the response! This makes sense - I suspected it was async but I wasn't sure if it was working as intended.

Given the fuse limitation, do you have guidance on how to block on in-flight writes? Would it be better to run `mount-s3` in the foreground and wait for the process to exit?

**Comment by passaro** [comment] 2023-08-08 16:08
Yes, waiting for `mount-s3` to exit will work. That's because Mountpoint will process all pending requests before terminating.

We should mention this in the docs and clarify the behavior on `umount`.

**Closed** 2023-08-08 20:33 UTC
Labels: bug
