### ISSUE TITLE
Mountpoint_s3::fuse: release failed

### ISSUE THREAD

**Issue by djhenry2** [awslabs/mountpoint-s3#670] opened 2023-12-07 15:08 UTC
### Mountpoint for Amazon S3 version

mount-s3 1.1.1

### AWS Region

us-east-2

### Describe the running environment

Ubuntu 22.04 mounting S3 bucket in the same account.

### What happened?

Many errors with "Mountpoint_s3::fuse: release failed"

Mount command:
mount-s3 --allow-root  --read-only --log-directory /var/log/mountpoint-s3/ sftpgw-i-***** wn-s3   (bucket name hidden)

### Relevant log output

[mountpoint-s3-2023-12-07T13-52-09Z.log](https://github.com/awslabs/mountpoint-s3/files/13601607/mountpoint-s3-2023-12-07T13-52-09Z.log)

**Comment by dannycjones** [comment] 2023-12-07 17:06
Thanks for reporting this. I see its similar to the issue in #582. Thanks for sharing the logs, that should help with a reproduction I hope.

@djhenry2 Can you share any impact to your workload? Is it causing issues or currently just warnings in the logs (which we should fix).

**Comment by dannycjones** [comment] 2024-01-19 13:13
We released a possible fix for this in v1.3.2. @djhenry2, can you give it a try and check its solved for your use case?

The fix is to remove a race condition related to file handle de-allocation (https://github.com/awslabs/mountpoint-s3/commit/6e7252dd2e54932e277e5b5ee7000f9bc816a682). There was a chance that before file handles references were released from an operation like `read` or `fsync`, the `release` request would arrive and be unable to de-allocate the file handle. This meant that the file handle would be left in the file handle table, and could lead to increased memory usage since the file handles hold on to prefetched file content.

**Comment by sauraank** [comment] 2024-02-06 00:44
I am closing this issue due to inactivity. If you any further information or question, please re-open this issue or create a new issue. Thanks.

**Closed by sauraank** 2024-02-06 00:44 UTC
Labels: bug
