### ISSUE TITLE
Unknown response error -- Error 6146 -- using AWS_PROFILE env var

### ISSUE THREAD

**Issue by ooboyle-rs10** [awslabs/mountpoint-s3#206] opened 2023-04-12 13:09 UTC
### Mountpoint for Amazon S3 version

mountpoint-s3 0.2.0-7010b0d

### AWS Region

us-east-1

### Describe the running environment

Running on Debian laptop trying to access a bucket in us-east-1.

### What happened?

I receive an Unknown Response error. I'm trying to use the AWS_PROFILE env var so I can assume a role. The env var is being picked up but the profile it points to in ~/.aws/config is not.

$ ./mount-s3 myBucket ~/mnt --region us-east-1

Error: Failed to create S3 client

Unknown response error: MetaRequestResult { response_status: 0, crt_error: Error(6146, "aws-c-auth: AWS_AUTH_SIGNING_NO_CREDENTIALS, Attempt to sign an http request without credentials"), error_response_headers: None, error_response_body: None }
Error: Failed to create mount process

### Relevant log output

```shell
2023-04-11T19:23:30.008411Z ERROR awscrt::socket: id=0x7f95d0000d50 fd=16: timed out, shutting down.
2023-04-11T19:23:30.008620Z ERROR awscrt::socket: id=0x7f95d0000d50 fd=-1: connection failure
2023-04-11T19:23:30.008674Z ERROR awscrt::channel-bootstrap: id=0x55c8cc756930: Connection failed with error_code 1048.
2023-04-11T19:23:30.008691Z ERROR awscrt::http-connection: static: Client connection failed with error 1048 (AWS_IO_SOCKET_TIMEOUT).
2023-04-11T19:23:30.008767Z ERROR awscrt::Unknown: (id=0x55c8cc752910) IMDS client failed to update the token from IMDS.
2023-04-11T19:23:33.009622Z ERROR awscrt::socket: id=0x7f95c8000d50 fd=16: timed out, shutting down.
2023-04-11T19:23:33.009779Z ERROR awscrt::socket: id=0x7f95c8000d50 fd=-1: connection failure
2023-04-11T19:23:33.009835Z ERROR awscrt::channel-bootstrap: id=0x55c8cc756930: Connection failed with error_code 1048.
2023-04-11T19:23:33.009851Z ERROR awscrt::http-connection: static: Client connection failed with error 1048 (AWS_IO_SOCKET_TIMEOUT).
2023-04-11T19:23:33.021284Z ERROR awscrt::AuthCredentialsProvider: static: Profile credentials provider could not load a profile at TEST-PROFILE
2023-04-11T19:23:33.021326Z ERROR awscrt::AuthCredentialsProvider: Failed to build config profile collection from file at (/home/user/.aws/config) : Success.
2023-04-11T19:23:33.021333Z ERROR awscrt::AuthCredentialsProvider: Failed to resolve either region, role arn or token file path during sts web identity provider initialization.
2023-04-11T19:23:35.029520Z ERROR awscrt::socket: id=0x7f95c0001050 fd=25: timed out, shutting down.
2023-04-11T19:23:35.029705Z ERROR awscrt::socket: id=0x7f95c0001050 fd=-1: connection failure
2023-04-11T19:23:35.029759Z ERROR awscrt::channel-bootstrap: id=0x55c8cc78a880: Connection failed with error_code 1048.
2023-04-11T19:23:35.029776Z ERROR awscrt::http-connection: static: Client connection failed with error 1048 (AWS_IO_SOCKET_TIMEOUT).
2023-04-11T19:23:35.029871Z ERROR awscrt::Unknown: (id=0x55c8cc8a6340) IMDS client failed to update the token from IMDS.
2023-04-11T19:23:38.030305Z ERROR awscrt::socket: id=0x7f95d0002780 fd=24: timed out, shutting down.
2023-04-11T19:23:38.030449Z ERROR awscrt::socket: id=0x7f95d0002780 fd=-1: connection failure
2023-04-11T19:23:38.092996Z ERROR awscrt::channel-bootstrap: id=0x55c8cc78a880: Connection failed with error_code 1048.
2023-04-11T19:23:38.093051Z ERROR awscrt::http-connection: static: Client connection failed with error 1048 (AWS_IO_SOCKET_TIMEOUT).
2023-04-11T19:23:38.093146Z ERROR awscrt::AuthCredentialsProvider: (id=0x55c8cc78a760) Default chain credentials provider failed to source credentials with error 6153(aws-c-auth: AWS_AUTH_CREDENTIALS_PROVIDER_IMDS_SOURCE_FAILURE, Valid credentials could not be sourced by the IMDS provider)
2023-04-11T19:23:38.093174Z ERROR awscrt::AuthSigning: (id=0x7f95b4001170) Credentials Provider failed to source credentials with error 6153(aws-c-auth: AWS_AUTH_CREDENTIALS_PROVIDER_IMDS_SOURCE_FAILURE, Valid credentials could not be sourced by the IMDS provider)
2023-04-11T19:23:38.093191Z ERROR awscrt::S3MetaRequest: id=0x55c8cc8ad710 Meta request could not sign TTP request due to error code 6146 (Attempt to sign an http request without credentials)
```

**Comment by dannycjones** [comment] 2023-04-14 07:48
Hey @ooboyle-rs10, sorry you're seeing this error.

It seems to me that there's some error parsing the configuration entry. Does the configuration work with other AWS SDKs or the AWS CLI? For example, does the following work as expected?

```
AWS_PROFILE=<your-profile> aws sts get-caller-identity
```

If possible, please provide the contents (full, or if not possible a subset/redacted) of the `.aws/config` file?

I think reviewing the contents of the config will be most useful to understand the issue. However to help speed up resolution, can you please also provide some more logging using the below configuration. Details about using the `RUST_LOG` environment variable can be found here: https://github.com/awslabs/mountpoint-s3/blob/main/doc/LOGGING.md#log-details

```
RUST_LOG=debug,awscrt=warn,awscrt::AuthCredentialsProvider=debug,awscrt::http-stream=debug
```

**Comment by ooboyle-rs10** [comment] 2023-04-14 14:07
Hi, thanks for picking this up.

I agree with you. And I've also figured out why:

After adding the rust debug env var, I noticed that the client was loading the first non-default profile from the config file. The profile I am using in the AWS_PROFILE var is the second profile in the config. I took the following steps to troubleshoot:

1) re-ordered the profiles so that the correct one preceded the incorrect one
2) added a region parameter to the correct profile
3) added the same number of spaces in front of the region parameter from the default profile
4) replaced spaces with a single tab
5) removed all spaces and tabs

Number 5 is the winner. The client doesn't correct parse spaces or tabs in front of profile parameters. At this time, it requires no spaces or tabs to correctly load the profile.

Answers to your questions, in case they are still useful to you:

This profile and the others in the .aws/config file all work as expected with aws cli. Here's the output of the get-caller-identity. It's showing the profile I've set in the AWS_PROFILE env var. 

{
    "UserId": "ARDAJECBQCD76TPJ5EDFQ:botocore-session-1681478594",
    "Account": "123456789012",
    "Arn": "arn:aws:sts::123456789012:assumed-role/MY-ROLE/botocore-session-1681478594"
}

MY-ROLE exists in a sub-account of an Organization. The IAM user exists in the root account and assumes the role. The IAM user's creds in .aws/credentials work everywhere else.

Here's a redacted version of the config file:

[default]
region = us-east-1

[profile FIRST-PROFILE-IN-CONFIG]
    role_arn = arn:aws:iam::123456789012:role/INCORRECT-ROLE
    source_profile = default

[profile TEST-PROFILE]
    role_arn = arn:aws:iam::123456789012:role/MY-ROLE
    source_profile = default

Log output:

2023-04-14T13:37:07.491358Z ERROR awscrt::socket: id=0x7f6088000d50 fd=16: timed out, shutting down.    
2023-04-14T13:37:07.491603Z ERROR awscrt::socket: id=0x7f6088000d50 fd=-1: connection failure    
2023-04-14T13:37:07.491665Z ERROR awscrt::channel-bootstrap: id=0x555c0a7baa00: Connection failed with error_code 1048.    
2023-04-14T13:37:07.491684Z ERROR awscrt::http-connection: static: Client connection failed with error 1048 (AWS_IO_SOCKET_TIMEOUT).    
2023-04-14T13:37:07.491703Z  WARN awscrt::connection-manager: id=0x555c0a7bbef0: Failed to obtain new connection from http layer, error 1048(socket operation timed out.)    
2023-04-14T13:37:07.491733Z  WARN awscrt::connection-manager: id=0x555c0a7bbef0: Failed to complete connection acquisition with error_code 1048(socket operation timed out.)    
2023-04-14T13:37:07.491767Z  WARN awscrt::Unknown: id=0x555c0a7aa640: IMDS Client failed to acquire a connection, error code 1048(socket operation timed out.)    
2023-04-14T13:37:07.491809Z ERROR awscrt::Unknown: (id=0x555c0a7aa640) IMDS client failed to update the token from IMDS.    
2023-04-14T13:37:10.492258Z ERROR awscrt::socket: id=0x7f6084000d50 fd=16: timed out, shutting down.    
2023-04-14T13:37:10.492455Z ERROR awscrt::socket: id=0x7f6084000d50 fd=-1: connection failure    
2023-04-14T13:37:10.492571Z ERROR awscrt::channel-bootstrap: id=0x555c0a7baa00: Connection failed with error_code 1048.    
2023-04-14T13:37:10.492601Z ERROR awscrt::http-connection: static: Client connection failed with error 1048 (AWS_IO_SOCKET_TIMEOUT).    
2023-04-14T13:37:10.492621Z  WARN awscrt::connection-manager: id=0x555c0a7bbef0: Failed to obtain new connection from http layer, error 1048(socket operation timed out.)    
2023-04-14T13:37:10.492651Z  WARN awscrt::connection-manager: id=0x555c0a7bbef0: Failed to complete connection acquisition with error_code 1048(socket operation timed out.)    
2023-04-14T13:37:10.492715Z  WARN awscrt::Unknown: id=0x555c0a7aa640: IMDS Client failed to acquire a connection, error code 1048(socket operation timed out.)    
2023-04-14T13:37:10.493050Z  WARN mount_s3: failed to detect network throughput: failed to retrieve instance type

Caused by:
    0: IMDS query failed
    1: Unknown CRT error
    2: CRT error 1048: aws-c-io: AWS_IO_SOCKET_TIMEOUT, socket operation timed out.
2023-04-14T13:37:10.493127Z  INFO mount_s3: target network throughput 10 Gbps
2023-04-14T13:37:10.495818Z DEBUG mountpoint_s3_client::endpoint: selected endpoint endpoint="https://s3.us-east-1.amazonaws.com" addressing_style=Automatic
2023-04-14T13:37:10.496308Z  INFO awscrt::AuthCredentialsProvider: (id=0x555c0a845b40): TLS context not provided, initializing a new one for credentials provider.    
2023-04-14T13:37:10.503792Z  WARN awscrt::AWSProfile: Property continuation seen outside of a current property    
2023-04-14T13:37:10.503804Z  WARN awscrt::AWSProfile: Profile Parse context:
 Source File:/home/user/.aws/config
 Line: 5
 Current Profile: FIRST-PROFILE-IN-CONFIG-FILE
 Current Property: <None>    
2023-04-14T13:37:10.503809Z  WARN awscrt::AWSProfile: Fatal error while parsing aws profile collection    
2023-04-14T13:37:10.503829Z  WARN awscrt::AWSProfile: property "aws_access_key_id" has value "" replaced during merge    
2023-04-14T13:37:10.503835Z  WARN awscrt::AWSProfile: property "aws_secret_access_key" has value "" replaced during merge    
2023-04-14T13:37:10.503840Z ERROR awscrt::AuthCredentialsProvider: static: Profile credentials provider could not load a profile at TEST-PROFILE.    
2023-04-14T13:37:10.503859Z  WARN awscrt::AWSProfile: Property continuation seen outside of a current property    
2023-04-14T13:37:10.503865Z  WARN awscrt::AWSProfile: Profile Parse context:
 Source File:/home/user/.aws/config
 Line: 5
 Current Profile: FIRST-PROFILE-IN-CONFIG-FILE
 Current Property: <None>    
2023-04-14T13:37:10.503869Z  WARN awscrt::AWSProfile: Fatal error while parsing aws profile collection    
2023-04-14T13:37:10.503874Z ERROR awscrt::AuthCredentialsProvider: Failed to build config profile collection from file at (/home/user/.aws/config) : Success.    
2023-04-14T13:37:10.503888Z ERROR awscrt::AuthCredentialsProvider: Failed to resolve either region, role arn or token file path during sts web identity provider initialization.    
2023-04-14T13:37:10.510881Z DEBUG head_bucket{id=0}: mountpoint_s3_client::s3_crt_client::head_bucket: new request bucket="ahr-salt-us-east-1" endpoint=Endpoint { uri: Uri("https://s3.us-east-1.amazonaws.com"), addressing_style: Automatic }
2023-04-14T13:37:10.511283Z DEBUG awscrt::AuthCredentialsProvider: (id=0x555c0a845b40) Credentials provider chain get credentials dispatch    
2023-04-14T13:37:10.511301Z  INFO awscrt::AuthCredentialsProvider: (id=0x555c0a83a160) Cached credentials provider has expired credentials.  Requerying.    
2023-04-14T13:37:10.511307Z DEBUG awscrt::AuthCredentialsProvider: (id=0x555c0a7c4bd0) Credentials provider chain get credentials dispatch    
2023-04-14T13:37:10.511313Z DEBUG awscrt::AuthCredentialsProvider: (id=0x555c0a7c4bd0) Credentials provider chain callback 1 invoked with invalid credentials and error code 6150    
2023-04-14T13:37:10.511322Z DEBUG awscrt::AuthCredentialsProvider: (id=0x555c0a7c4bd0) Credentials provider chain invoking chain member #1    
2023-04-14T13:37:12.512297Z ERROR awscrt::socket: id=0x7f6070000d50 fd=25: timed out, shutting down.    
2023-04-14T13:37:12.512458Z ERROR awscrt::socket: id=0x7f6070000d50 fd=-1: connection failure    
2023-04-14T13:37:12.512511Z ERROR awscrt::channel-bootstrap: id=0x555c0a845c60: Connection failed with error_code 1048.    
2023-04-14T13:37:12.512529Z ERROR awscrt::http-connection: static: Client connection failed with error 1048 (AWS_IO_SOCKET_TIMEOUT).    
2023-04-14T13:37:12.512545Z  WARN awscrt::connection-manager: id=0x555c0a98fdc0: Failed to obtain new connection from http layer, error 1048(socket operation timed out.)    
2023-04-14T13:37:12.512574Z  WARN awscrt::connection-manager: id=0x555c0a98fdc0: Failed to complete connection acquisition with error_code 1048(socket operation timed out.)    
2023-04-14T13:37:12.512588Z  WARN awscrt::Unknown: id=0x555c0a98fcc0: IMDS Client failed to acquire a connection, error code 1048(socket operation timed out.)    
2023-04-14T13:37:12.512629Z ERROR awscrt::Unknown: (id=0x555c0a98fcc0) IMDS client failed to update the token from IMDS.    
2023-04-14T13:37:15.490016Z  INFO mountpoint_s3::aggregate_metrics: s3.client.num_auto_default_network_io: 0 (n=1)
2023-04-14T13:37:15.490113Z  INFO mountpoint_s3::aggregate_metrics: s3.client.num_auto_ranged_copy_network_io: 0 (n=1)
2023-04-14T13:37:15.490125Z  INFO mountpoint_s3::aggregate_metrics: s3.client.num_auto_ranged_get_network_io: 0 (n=1)
2023-04-14T13:37:15.490134Z  INFO mountpoint_s3::aggregate_metrics: s3.client.num_auto_ranged_put_network_io: 0 (n=1)
2023-04-14T13:37:15.490142Z  INFO mountpoint_s3::aggregate_metrics: s3.client.num_requests_being_prepared: 0 (n=1)
2023-04-14T13:37:15.490150Z  INFO mountpoint_s3::aggregate_metrics: s3.client.num_requests_being_processed: 0 (n=1)
2023-04-14T13:37:15.490159Z  INFO mountpoint_s3::aggregate_metrics: s3.client.num_requests_stream_queued_waiting: 0 (n=1)
2023-04-14T13:37:15.490167Z  INFO mountpoint_s3::aggregate_metrics: s3.client.num_requests_streaming: 0 (n=1)
2023-04-14T13:37:15.490175Z  INFO mountpoint_s3::aggregate_metrics: s3.client.num_total_network_io: 0 (n=1)
2023-04-14T13:37:15.490183Z  INFO mountpoint_s3::aggregate_metrics: s3.client.request_queue_size: 0 (n=1)
2023-04-14T13:37:15.512841Z ERROR awscrt::socket: id=0x7f607c002620 fd=24: timed out, shutting down.    
2023-04-14T13:37:15.512989Z ERROR awscrt::socket: id=0x7f607c002620 fd=-1: connection failure    
2023-04-14T13:37:15.513053Z ERROR awscrt::channel-bootstrap: id=0x555c0a845c60: Connection failed with error_code 1048.    
2023-04-14T13:37:15.513071Z ERROR awscrt::http-connection: static: Client connection failed with error 1048 (AWS_IO_SOCKET_TIMEOUT).    
2023-04-14T13:37:15.513088Z  WARN awscrt::connection-manager: id=0x555c0a98fdc0: Failed to obtain new connection from http layer, error 1048(socket operation timed out.)    
2023-04-14T13:37:15.513143Z  WARN awscrt::connection-manager: id=0x555c0a98fdc0: Failed to complete connection acquisition with error_code 1048(socket operation timed out.)    
2023-04-14T13:37:15.513182Z  WARN awscrt::Unknown: id=0x555c0a98fcc0: IMDS Client failed to acquire a connection, error code 1048(socket operation timed out.)    
2023-04-14T13:37:15.513210Z  INFO awscrt::AuthCredentialsProvider: (id=0x555c0a7c4bd0) Credentials provider chain callback terminating on index 2, with invalid credentials and error code 6153    
2023-04-14T13:37:15.513235Z DEBUG awscrt::AuthCredentialsProvider: (id=0x555c0a83a160) Cached credentials provider next refresh time set to 1727450429085255    
2023-04-14T13:37:15.513253Z DEBUG awscrt::AuthCredentialsProvider: (id=0x555c0a83a160) Cached credentials provider was unable to source credentials on refresh    
2023-04-14T13:37:15.513265Z DEBUG awscrt::AuthCredentialsProvider: (id=0x555c0a83a160) Cached credentials provider notifying pending queries of new credentials    
2023-04-14T13:37:15.513282Z ERROR awscrt::AuthCredentialsProvider: (id=0x555c0a845b40) Default chain credentials provider failed to source credentials with error 6153(aws-c-auth: AWS_AUTH_CREDENTIALS_PROVIDER_IMDS_SOURCE_FAILURE, Valid credentials could not be sourced by the IMDS provider)    
2023-04-14T13:37:15.513313Z ERROR awscrt::AuthSigning: (id=0x7f6068001170) Credentials Provider failed to source credentials with error 6153(aws-c-auth: AWS_AUTH_CREDENTIALS_PROVIDER_IMDS_SOURCE_FAILURE, Valid credentials could not be sourced by the IMDS provider)    
2023-04-14T13:37:15.513330Z ERROR awscrt::S3MetaRequest: id=0x555c0a997670 Meta request could not sign TTP request due to error code 6146 (Attempt to sign an http request without credentials)    
2023-04-14T13:37:15.513532Z DEBUG head_bucket{id=0}: mountpoint_s3_client::s3_crt_client: request failed request_id="unknown" duration_us=5002629 request_result=MetaRequestResult { response_status: 0, crt_error: Error(6146, "aws-c-auth: AWS_AUTH_SIGNING_NO_CREDENTIALS, Attempt to sign an http request without credentials"), error_response_headers: None, error_response_body: None }
2023-04-14T13:37:15.513942Z  INFO mountpoint_s3::aggregate_metrics: s3.meta_request_failures[op=head_bucket,status=-6146]: 1
2023-04-14T13:37:15.513996Z  INFO mountpoint_s3::aggregate_metrics: s3.meta_requests[op=head_bucket]: 1

**Comment by ooboyle-rs10** [comment] 2023-04-14 14:34
Also, I'd like to use this in production but I can't depend on the env var method and need a --profile option like aws cli has. I saw another issue indicating such a feature was planned. Any idea when that might appear?

**Comment by dannycjones** [comment] 2023-04-14 14:42
> Also, I'd like to use this in production but I can't depend on the env var method and need a --profile option like aws cli has. I saw another issue indicating such a feature was planned. Any idea when that might appear?

Sure, the issue is open at #151. Thanks for sharing that its important to your use case to specify as an argument - it helps us prioritize.

I believe there are some draft changes in PR #209, so I would keep an eye on that PR.

**Comment by dannycjones** [comment] 2023-04-14 14:50
Thanks for providing those logs, and sharing how you mitigated the issue.

To confirm, it appears that one or more spaces before a configuration field causes that profile entry to not be parsed. I was able to reproduce as well.

**Comment by ooboyle-rs10** [comment] 2023-04-14 14:56
Exactly. Thanks, Danny. I'll keep an eye on #151 and #209.

**Comment by jamesbornholt** [comment] 2023-04-14 14:59
Thanks for the awesome debugging! It does seem like the CRT profile parser is only trying to strip whitespace from the back of the key, not the front: https://github.com/awslabs/aws-c-sdkutils/blob/9de59230f025df2745b098feda3611f9667e5a35/source/aws_profile.c#L1131

On the other hand, boto3 uses Python's [configparser](https://docs.python.org/3/library/configparser.html), which does strip:
```python
import configparser
p = configparser.RawConfigParser()
p.read_string("[profile foo]\n    key = val\n")
print(p.get("profile foo", "key"))  # prints "val"
```

Seems like a divergence we should get fixed in the CRT.

**Comment by jamesbornholt** [comment] 2023-04-14 20:21
Actually, poking around some more, I think boto3 might be the odd one out here. Other SDKs don't allow whitespace at the start of a line:
* Java: https://github.com/aws/aws-sdk-java-v2/blob/282158892480a40fed0d5d1043690a13a28e772e/core/profiles/src/main/java/software/amazon/awssdk/profiles/internal/ProfileFileReader.java#L160
* Rust: https://github.com/awslabs/smithy-rs/blob/35f2f27a8380a1310c264a386e162cd9f2180137/aws/rust-runtime/aws-config/src/profile/parser/parse.rs#L194
* Ruby: https://github.com/aws/aws-sdk-ruby/blob/e25d508b4fbe970e7035bc41770d1a5eaa91fdf4/gems/aws-sdk-core/lib/aws-sdk-core/ini_parser.rb#L23

I don't think this is well documented anywhere, and it's kind of an unfortunate divergence.

**Comment by jamesbornholt** [comment] 2023-04-21 16:29
Awesome, thanks for confirming!

**Closed by jamesbornholt** 2023-04-21 16:29 UTC
Labels: bug
