### ISSUE TITLE
Folder disappears after deleting all files contained within it

### ISSUE THREAD

**Issue by revanhernandy** [awslabs/mountpoint-s3#682] opened 2023-12-21 08:50 UTC
### Mountpoint for Amazon S3 version

mount-s3 1.3.1

### AWS Region

eu-central-1

### Describe the running environment

EC2 Ubuntu 22.04

### Mountpoint options

```shell
/usr/bin/mount-s3 mybucket /mymount --prefix ftp/ --allow-other --log-directory /var/log/mounts3-log --file-mode 0777 --dir-mode 0777 --allow-delete --auto-unmount --region eu-central-1
```

### What happened?

I mount the S3 for the chrooted FTP user home directory. After deleting some files inside, the folder is gone, and I cannot log in again due to the missing home directory. How can I prevent this?

### Relevant log output

```shell
2023-12-21T02:01:33.616379Z  WARN lookup{req=50092 ino=1 name="myfolder"}: mountpoint_s3::fuse: lookup failed: inode error: file does not exist
```

**Comment by dannycjones** [comment] 2023-12-27 11:06
Hey @revanhernandy. As @mschfh wrote, the objects are being grouped based on path. This is also described in our semantics documentation for reference: https://github.com/awslabs/mountpoint-s3/blob/83fa7c654623cba34b44f99c3b8930b693ebd0b1/doc/SEMANTICS.md#directories

One way to resolve your issue would be to create either an empty file for persisting a directory (similar to `.gitkeep` files for Git), or to create a directory marker. We don't recommended using directory markers generally since they can have adverse affects with larger workloads, but it may work best for your use case.

A directory marker is an empty object with the key matching the prefix of objects that would be contained within. For some directory "dir1", you could create an empty object `dir1/` which will be interpreted by many file-oriented connectors/views as a directory. For example, the S3 Console will create this type of object when creating a directory. Note that directory markers cannot be removed by Mountpoint today, and you would need to use another S3 client to remove them later.

---

Please let us know if this resolves your issue or if you need any further help with it.

**Comment by revanhernandy** [comment] 2023-12-27 11:54
Hi @dannycjones thank you for the response.  Got it and makes sense.
Currently, we have an Azure blobfuse filesystem and it can be handled by a temporary path but we need to migrate into S3 stuff 😄 it would be very perfect if Mount S3 could do similar. 
But, the first workaround is ideal in this case with making a persistence file with a dot(.) would be helpful in case, vsftpd by default would hide the files and directories starting with dot(.)

**Comment by dannycjones** [comment] 2024-02-01 10:12
>Currently, we have an Azure blobfuse filesystem and it can be handled by a temporary path but we need to migrate into S3 stuff 😄 it would be very perfect if Mount S3 could do similar.

Sorry @revanhernandy, I didn't understand what the ask is. What do you mean by a temporary path?

**Comment by dannycjones** [comment] 2024-02-01 10:12
We plan to add the scenario in this issue to a new FAQ/troubleshooting document we're creating, tracking this scenario here: #722.

**Comment by jamesbornholt** [comment] 2024-02-23 05:13
We'll update the troubleshooting documentation to mention this case, but as discussed above, this is the expected behavior. Creating a hidden `.keep` file is a good workaround. Thanks for the report!

**Closed by jamesbornholt** 2024-02-23 05:13 UTC
Labels: bug
